version: "3.9"

services:
  db:
    image: postgres
    container_name: database_dtmoney
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dtmoney
    volumes:
      - pgdata:/data/postgres
  redis:
    image: redis:alpine
    ports: 
      - 56379:6379 
  
volumes:
  pgdata:
    driver: local